### ISSUE TITLE
 ..

### ISSUE THREAD

**Issue by vinodjagwani** [timbuethe/tobo#1]

**Comment by timbuethe** [comment]
Hey vinodjagwani,

first of all, I appreciate that you finally deleted _our_ code from your Github account. Thank you.

Why you now go ahead and write your hateful comment here again, in one of my personal projects is a mystery to me. I think you should reconsider having something like this publicly available on Github. Imagine a future employer would stumble upon this.

You seem really frustrated about mytaxi rejecting your application, and I can understand your frustration because nobody likes rejection, but this is just unprofessional. 

Anyways, as far as I can remember I was not involved in your interview so why would you attack me personally?

All the best,
Tim

**Comment by vinodjagwani** [comment]
****

**Comment by vinodjagwani** [comment]
I upload the code without your company name.. since its modified by me, so its my property.
